### PR TITLE
addHMC and configureHMC error out for discrete-valued nodes

### PR DESCRIPTION
**Pull request by danielturek**
The title says it all.

### CODE REVIEW

**Comment by paciorek** [comment]
So the idea is to check for discrete nodes before the setup code of the HMC sampler (where it's also checked) is invoked?

**Comment by danielturek** [comment]
The idea is to have `configureHMC` and `addHMC` (utility functions) catch it earlier, if you try to add an HMC sampler to a discrete node.  This was important for some reason... honestly... although I'm blanking on it right now.

**Comment by paciorek** [comment]
I think it makes sense. I guess if one does `addSampler(..., type = 'HMC')` it won't get caught until the setup code for the HMC sampler?  So it will be caught at different times depending on how one configures the MCMC but there may be no way around that.

**Comment by danielturek** [comment]
@paciorek Yes, that's right, which reminds me of my original concern: Without these changes, in the case of a model with discrete latent states, `buildHMC` would generate an error, and `configureHMC` would generate an MCMC configuration object that will cause an error at the time of `buildMCMC`.  So, I do think these changes are important.

**Pull request merged**
